workflows:
  my-workflow:
    instance_type: mac_mini_m1
    environment:
      xcode: 14.0
    scripts:
      - name: Run iOS tests
        script: |
          set -e # exit on first failed command

          xcode-project run-tests \
              --project ContactApp.xcodeproj \
              --scheme ContactApp \
              --device "iPhone 13"
        test_report: build/ios/test/*.xml
